export const companyData: Record<string, any> = {
  zomato: {
    name: "Zomato",
    logo: "https://www.google.com/s2/favicons?domain=zomato.com&sz=128",
    category: "Food Delivery",
    change: "+2.35%",
    description:
      "Zomato is one of India's largest food delivery and restaurant discovery platforms, connecting millions of users with restaurants across the country.",
    founded: "2008",
    headquarters: "Gurugram, India",
    ceo: "Deepinder Goyal",
    valuation: "₹3,00,000-3,20,000 Cr",
    revenue: "₹9,877 Cr",
    users: "2.41 Cr+",
    funding: "₹19,000-38,000 Cr",
    employees: "25,900+",
  },
  swiggy: {
    name: "Swiggy",
    logo: "https://www.google.com/s2/favicons?domain=swiggy.com&sz=128",
    category: "Food Delivery",
    change: "+1.28%",
    description:
      "Swiggy is a leading on-demand food delivery and quick commerce platform operating in hundreds of cities across India.",
    founded: "2014",
    headquarters: "Bengaluru, India",
    ceo: "Sriharsha Majety",
    valuation: "₹93,000 Cr",
    revenue: "₹11,247 Cr",
    users: "7.2 Cr+",
    funding: "₹13,500 Cr",
    employees: "4,500+",
  },
  blinkit: {
    name: "Blinkit",
    logo: "https://www.google.com/s2/favicons?domain=blinkit.com&sz=128",
    category: "Quick Commerce",
    change: "+3.42%",
    description:
      "Blinkit (formerly Grofers) is a quick commerce platform delivering groceries and essentials within minutes, now owned by Zomato.",
    founded: "2013",
    headquarters: "Gurugram, India",
    ceo: "Albinder Dhindsa",
    valuation: "₹46,000 Cr",
    revenue: "₹2,301 Cr",
    users: "3.1 Cr+",
    funding: "₹4,200 Cr",
    employees: "2,000+",
  },
  zepto: {
    name: "Zepto",
    logo: "https://www.google.com/s2/favicons?domain=zeptonow.com&sz=128",
    category: "Quick Commerce",
    change: "+4.15%",
    description:
      "Zepto is a 10-minute grocery delivery startup that has rapidly scaled across major Indian cities with a dark-store model.",
    founded: "2021",
    headquarters: "Mumbai, India",
    ceo: "Aadit Palicha",
    valuation: "₹66,000 Cr",
    revenue: "₹4,454 Cr",
    users: "2.8 Cr+",
    funding: "₹10,800 Cr",
    employees: "1,800+",
  },
  paytm: {
    name: "Paytm",
    logo: "https://www.google.com/s2/favicons?domain=paytm.com&sz=128",
    category: "FinTech",
    change: "+0.85%",
    description:
      "Paytm is India's pioneering digital payments and financial services platform offering wallets, banking, and lending products.",
    founded: "2010",
    headquarters: "Noida, India",
    ceo: "Vijay Shekhar Sharma",
    valuation: "₹60,000 Cr",
    revenue: "₹9,978 Cr",
    users: "30 Cr+",
    funding: "₹20,000 Cr",
    employees: "9,000+",
  },
  flipkart: {
    name: "Flipkart",
    logo: "https://www.google.com/s2/favicons?domain=flipkart.com&sz=128",
    category: "E-commerce",
    change: "+1.92%",
    description:
      "Flipkart is one of India's largest e-commerce marketplaces, offering everything from electronics to fashion and groceries.",
    founded: "2007",
    headquarters: "Bengaluru, India",
    ceo: "Kalyan Krishnamurthy",
    valuation: "₹3,00,000 Cr",
    revenue: "₹66,000 Cr",
    users: "45 Cr+",
    funding: "₹1,50,000 Cr",
    employees: "50,000+",
  },
  amazon: {
    name: "Amazon India",
    logo: "https://www.google.com/s2/favicons?domain=amazon.com&sz=128",
    category: "E-commerce",
    change: "+0.45%",
    description:
      "Amazon India is the Indian arm of the global e-commerce giant, offering a massive marketplace, Prime Video, and AWS cloud services.",
    founded: "2013",
    headquarters: "Bengaluru, India",
    ceo: "Andy Jassy (Global)",
    valuation: "₹4,50,000 Cr",
    revenue: "₹74,000 Cr",
    users: "50 Cr+",
    funding: "—",
    employees: "1,00,000+",
  },
  nykaa: {
    name: "Nykaa",
    logo: "https://www.google.com/s2/favicons?domain=nykaa.com&sz=128",
    category: "Beauty E-commerce",
    change: "+2.10%",
    description:
      "Nykaa is India's leading beauty and personal care e-commerce platform, also expanding into fashion and luxury retail.",
    founded: "2012",
    headquarters: "Mumbai, India",
    ceo: "Falguni Nayar",
    valuation: "₹38,000 Cr",
    revenue: "₹6,400 Cr",
    users: "3.5 Cr+",
    funding: "₹3,000 Cr",
    employees: "3,000+",
  },
};