export const companyData: Record<string, any> = {
  zomato: {
    name: "Zomato",
    logo: "https://www.google.com/s2/favicons?domain=zomato.com&sz=128",
    category: "Food Delivery",
    change: "+2.35%",
    description:
      "Zomato is one of India's largest food delivery and restaurant discovery platforms, connecting millions of users with restaurants across the country.",
    founded: "2008",
    headquarters: "Gurugram, India",
    ceo: "Deepinder Goyal",
    valuation: "₹3,00,000-3,20,000 Cr",
    revenue: "₹9,877 Cr",
    users: "2.41 Cr+",
    funding: "₹19,000-38,000 Cr",
    employees: "25,900+",
  },
  swiggy: {
    name: "Swiggy",
    logo: "https://www.google.com/s2/favicons?domain=swiggy.com&sz=128",
    category: "Food Delivery",
    change: "+1.28%",
    description:
      "Swiggy is a leading on-demand food delivery and quick commerce platform operating in hundreds of cities across India.",
    founded: "2014",
    headquarters: "Bengaluru, India",
    ceo: "Sriharsha Majety",
    valuation: "₹93,000 Cr",
    revenue: "₹11,247 Cr",
    users: "7.2 Cr+",
    funding: "₹13,500 Cr",
    employees: "4,500+",
  },
  blinkit: {
    name: "Blinkit",
    logo: "https://www.google.com/s2/favicons?domain=blinkit.com&sz=128",
    category: "Quick Commerce",
    change: "+3.42%",
    description:
      "Blinkit (formerly Grofers) is a quick commerce platform delivering groceries and essentials within minutes, now owned by Zomato.",
    founded: "2013",
    headquarters: "Gurugram, India",
    ceo: "Albinder Dhindsa",
    valuation: "₹46,000 Cr",
    revenue: "₹2,301 Cr",
    users: "3.1 Cr+",
    funding: "₹4,200 Cr",
    employees: "2,000+",
  },
  zepto: {
    name: "Zepto",
    logo: "https://www.google.com/s2/favicons?domain=zeptonow.com&sz=128",
    category: "Quick Commerce",
    change: "+4.15%",
    description:
      "Zepto is a 10-minute grocery delivery startup that has rapidly scaled across major Indian cities with a dark-store model.",
    founded: "2021",
    headquarters: "Mumbai, India",
    ceo: "Aadit Palicha",
    valuation: "₹66,000 Cr",
    revenue: "₹4,454 Cr",
    users: "2.8 Cr+",
    funding: "₹10,800 Cr",
    employees: "1,800+",
  },
  paytm: {
    name: "Paytm",
    logo: "https://www.google.com/s2/favicons?domain=paytm.com&sz=128",
    category: "FinTech",
    change: "+0.85%",
    description:
      "Paytm is India's pioneering digital payments and financial services platform offering wallets, banking, and lending products.",
    founded: "2010",
    headquarters: "Noida, India",
    ceo: "Vijay Shekhar Sharma",
    valuation: "₹60,000 Cr",
    revenue: "₹9,978 Cr",
    users: "30 Cr+",
    funding: "₹20,000 Cr",
    employees: "9,000+",
  },
  flipkart: {
    name: "Flipkart",
    logo: "https://www.google.com/s2/favicons?domain=flipkart.com&sz=128",
    category: "E-commerce",
    change: "+1.92%",
    description:
      "Flipkart is one of India's largest e-commerce marketplaces, offering everything from electronics to fashion and groceries.",
    founded: "2007",
    headquarters: "Bengaluru, India",
    ceo: "Kalyan Krishnamurthy",
    valuation: "₹3,00,000 Cr",
    revenue: "₹66,000 Cr",
    users: "45 Cr+",
    funding: "₹1,50,000 Cr",
    employees: "50,000+",
  },
  amazon: {
    name: "Amazon India",
    logo: "https://www.google.com/s2/favicons?domain=amazon.com&sz=128",
    category: "E-commerce",
    change: "+0.45%",
    description:
      "Amazon India is the Indian arm of the global e-commerce giant, offering a massive marketplace, Prime Video, and AWS cloud services.",
    founded: "2013",
    headquarters: "Bengaluru, India",
    ceo: "Andy Jassy (Global)",
    valuation: "₹4,50,000 Cr",
    revenue: "₹74,000 Cr",
    users: "50 Cr+",
    funding: "—",
    employees: "1,00,000+",
  },
  nykaa: {
    name: "Nykaa",
    logo: "https://www.google.com/s2/favicons?domain=nykaa.com&sz=128",
    category: "Beauty E-commerce",
    change: "+2.10%",
    description:
      "Nykaa is India's leading beauty and personal care e-commerce platform, also expanding into fashion and luxury retail.",
    founded: "2012",
    headquarters: "Mumbai, India",
    ceo: "Falguni Nayar",
    valuation: "₹38,000 Cr",
    revenue: "₹6,400 Cr",
    users: "3.5 Cr+",
    funding: "₹3,000 Cr",
    employees: "3,000+",
  },
  
  byju: {
    name: "BYJU'S",
    logo: "https://www.google.com/s2/favicons?domain=byjus.com&sz=128",
    category: "EdTech",
    change: "+1.45%",
    description: "BYJU'S is India's largest edtech company offering personalized learning programs for students from K-12 to competitive exam preparation.",
    founded: "2011",
    headquarters: "Bengaluru, India",
    ceo: "Byju Raveendran",
    valuation: "₹74,000 Cr",
    revenue: "₹5,014 Cr",
    users: "15 Cr+",
    funding: "₹24,000 Cr",
    employees: "50,000+",
  },
  unacademy: {
    name: "Unacademy",
    logo: "https://www.google.com/s2/favicons?domain=unacademy.com&sz=128",
    category: "EdTech",
    change: "+0.92%",
    description: "Unacademy is a leading online learning platform offering live classes and courses for competitive exams like UPSC, JEE, and NEET.",
    founded: "2015",
    headquarters: "Bengaluru, India",
    ceo: "Gaurav Munjal",
    valuation: "₹24,000 Cr",
    revenue: "₹1,000 Cr",
    users: "6 Cr+",
    funding: "₹8,500 Cr",
    employees: "8,000+",
  },
  practo: {
    name: "Practo",
    logo: "https://www.google.com/s2/favicons?domain=practo.com&sz=128",
    category: "HealthTech",
    change: "+1.10%",
    description: "Practo is India's leading healthtech platform connecting patients with doctors, offering online consultations, pharmacy, and diagnostics.",
    founded: "2008",
    headquarters: "Bengaluru, India",
    ceo: "Shashank ND",
    valuation: "₹8,000 Cr",
    revenue: "₹180 Cr",
    users: "10 Cr+",
    funding: "₹3,200 Cr",
    employees: "2,500+",
  },
  pharmeasy: {
    name: "PharmEasy",
    logo: "https://www.google.com/s2/favicons?domain=pharmeasy.in&sz=128",
    category: "HealthTech",
    change: "+2.30%",
    description: "PharmEasy is one of India's largest online pharmacy and healthcare platforms offering medicines, diagnostics, and teleconsultations.",
    founded: "2015",
    headquarters: "Mumbai, India",
    ceo: "Siddhart Shah",
    valuation: "₹18,000 Cr",
    revenue: "₹5,600 Cr",
    users: "2 Cr+",
    funding: "₹12,000 Cr",
    employees: "4,000+",
  },
  makemytrip: {
    name: "MakeMyTrip",
    logo: "https://www.google.com/s2/favicons?domain=makemytrip.com&sz=128",
    category: "Travel",
    change: "+1.75%",
    description: "MakeMyTrip is India's leading online travel company offering flight, hotel, holiday, and bus bookings across India and internationally.",
    founded: "2000",
    headquarters: "Gurugram, India",
    ceo: "Rajesh Magow",
    valuation: "₹25,000 Cr",
    revenue: "₹5,000 Cr",
    users: "5 Cr+",
    funding: "₹8,000 Cr",
    employees: "5,000+",
  },
  ola: {
    name: "Ola",
    logo: "https://www.google.com/s2/favicons?domain=olacabs.com&sz=128",
    category: "Travel",
    change: "+0.65%",
    description: "Ola is India's largest ride-hailing platform offering cab, auto, and bike rides across hundreds of cities, plus electric vehicles.",
    founded: "2010",
    headquarters: "Bengaluru, India",
    ceo: "Bhavish Aggarwal",
    valuation: "₹45,000 Cr",
    revenue: "₹2,800 Cr",
    users: "20 Cr+",
    funding: "₹18,000 Cr",
    employees: "10,000+",
  },
  hotstar: {
    name: "Hotstar",
    logo: "https://www.google.com/s2/favicons?domain=hotstar.com&sz=128",
    category: "Entertainment",
    change: "+1.20%",
    description: "Hotstar (Disney+ Hotstar) is India's largest streaming platform offering movies, TV shows, sports, and live events.",
    founded: "2015",
    headquarters: "Mumbai, India",
    ceo: "Sajith Sivanandan",
    valuation: "₹40,000 Cr",
    revenue: "₹2,000 Cr",
    users: "50 Cr+",
    funding: "—",
    employees: "1,500+",
  },
  spotify: {
    name: "Spotify India",
    logo: "https://www.google.com/s2/favicons?domain=spotify.com&sz=128",
    category: "Entertainment",
    change: "+0.55%",
    description: "Spotify is the world's largest music streaming platform with millions of songs, podcasts, and audiobooks available in India.",
    founded: "2019",
    headquarters: "Mumbai, India",
    ceo: "Amarjit Singh Batra",
    valuation: "₹12,000 Cr",
    revenue: "₹800 Cr",
    users: "8 Cr+",
    funding: "—",
    employees: "500+",
  },
  meesho: {
    name: "Meesho",
    logo: "https://www.google.com/s2/favicons?domain=meesho.com&sz=128",
    category: "E-commerce",
    change: "+2.80%",
    description: "Meesho is a social commerce platform enabling small businesses and individuals to sell products online with zero commission fees.",
    founded: "2015",
    headquarters: "Bengaluru, India",
    ceo: "Vidit Aatrey",
    valuation: "₹45,000 Cr",
    revenue: "₹5,734 Cr",
    users: "16 Cr+",
    funding: "₹9,000 Cr",
    employees: "6,000+",
  },
  myntra: {
    name: "Myntra",
    logo: "https://www.google.com/s2/favicons?domain=myntra.com&sz=128",
    category: "E-commerce",
    change: "+1.15%",
    description: "Myntra is India's leading fashion and lifestyle e-commerce platform, owned by Flipkart, offering clothing, accessories, and beauty products.",
    founded: "2007",
    headquarters: "Bengaluru, India",
    ceo: "Nandita Sinha",
    valuation: "₹35,000 Cr",
    revenue: "₹4,500 Cr",
    users: "9 Cr+",
    funding: "—",
    employees: "3,500+",
  },
  phonepe: {
    name: "PhonePe",
    logo: "https://www.google.com/s2/favicons?domain=phonepe.com&sz=128",
    category: "FinTech",
    change: "+1.65%",
    description: "PhonePe is India's largest digital payments platform offering UPI payments, insurance, mutual funds, and merchant services.",
    founded: "2015",
    headquarters: "Bengaluru, India",
    ceo: "Sameer Nigam",
    valuation: "₹1,00,000 Cr",
    revenue: "₹5,300 Cr",
    users: "55 Cr+",
    funding: "₹14,000 Cr",
    employees: "5,500+",
  },
  groww: {
    name: "Groww",
    logo: "https://www.google.com/s2/favicons?domain=groww.in&sz=128",
    category: "FinTech",
    change: "+2.05%",
    description: "Groww is one of India's largest investment platforms offering stocks, mutual funds, and fixed deposits with a simple, user-friendly app.",
    founded: "2016",
    headquarters: "Bengaluru, India",
    ceo: "Lalit Keshre",
    valuation: "₹65,000 Cr",
    revenue: "₹1,294 Cr",
    users: "10 Cr+",
    funding: "₹2,400 Cr",
    employees: "1,200+",
  },
  dunzo: {
    name: "Dunzo",
    logo: "https://www.google.com/s2/favicons?domain=dunzo.com&sz=128",
    category: "Quick Commerce",
    change: "+0.40%",
    description: "Dunzo is a hyperlocal delivery platform in India offering on-demand delivery of groceries, food, and packages within minutes.",
    founded: "2014",
    headquarters: "Bengaluru, India",
    ceo: "Kabeer Biswas",
    valuation: "₹6,000 Cr",
    revenue: "₹230 Cr",
    users: "1.5 Cr+",
    funding: "₹2,200 Cr",
    employees: "1,000+",
  },
  uber: {
    name: "Uber India",
    logo: "https://www.google.com/s2/favicons?domain=uber.com&sz=128",
    category: "Travel",
    change: "+0.88%",
    description: "Uber operates one of India's largest ride-hailing networks offering cabs, autos, and bike rides across major Indian cities.",
    founded: "2013",
    headquarters: "Bengaluru, India",
    ceo: "Prabhjeet Singh",
    valuation: "₹30,000 Cr",
    revenue: "₹2,200 Cr",
    users: "15 Cr+",
    funding: "—",
    employees: "2,000+",
  },
  netflix: {
    name: "Netflix India",
    logo: "https://www.google.com/s2/favicons?domain=netflix.com&sz=128",
    category: "Entertainment",
    change: "+0.95%",
    description: "Netflix is a global streaming giant offering movies, TV shows, and original content, with a growing subscriber base across India.",
    founded: "2016",
    headquarters: "Mumbai, India",
    ceo: "Monika Shergill",
    valuation: "₹20,000 Cr",
    revenue: "₹1,900 Cr",
    users: "1.2 Cr+",
    funding: "—",
    employees: "300+",
  },
  vedantu: {
    name: "Vedantu",
    logo: "https://www.google.com/s2/favicons?domain=vedantu.com&sz=128",
    category: "EdTech",
    change: "+0.70%",
    description: "Vedantu is a live online tutoring platform offering personalized learning for K-12 students and competitive exam preparation.",
    founded: "2014",
    headquarters: "Bengaluru, India",
    ceo: "Vamsi Krishna",
    valuation: "₹6,000 Cr",
    revenue: "₹280 Cr",
    users: "3 Cr+",
    funding: "₹2,400 Cr",
    employees: "2,000+",
  },
  apollo247: {
    name: "Apollo 24|7",
    logo: "https://www.google.com/s2/favicons?domain=apollo247.com&sz=128",
    category: "HealthTech",
    change: "+1.30%",
    description: "Apollo 24|7 is a digital healthcare platform by Apollo Hospitals offering online consultations, pharmacy, diagnostics, and health records.",
    founded: "2020",
    headquarters: "Chennai, India",
    ceo: "Sangita Reddy",
    valuation: "₹10,000 Cr",
    revenue: "₹450 Cr",
    users: "5 Cr+",
    funding: "—",
    employees: "1,500+",
  },
};